package com.kariscode.yike.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * 颜色令牌直接对齐前端原型，是为了让 Compose 页面与 `docs/frontend/material-app.css`
 * 使用同一套语义层级，避免每个 Feature 再各自定义一套“看起来差不多”的颜色。
 */
val YikePrimary = Color(0xFF0B6F69)
val YikeOnPrimary = Color(0xFFFFFFFF)
val YikePrimaryContainer = Color(0xFF9CF2EA)
val YikeOnPrimaryContainer = Color(0xFF00201D)
val YikePrimaryDark = Color(0xFF80D5CE)
val YikeOnPrimaryDark = Color(0xFF003734)
val YikePrimaryContainerDark = Color(0xFF00504B)
val YikeOnPrimaryContainerDark = Color(0xFF9CF2EA)
val YikeSecondary = Color(0xFF4B635F)
val YikeOnSecondary = Color(0xFFFFFFFF)
val YikeSecondaryContainer = Color(0xFFCEE8E3)
val YikeOnSecondaryContainer = Color(0xFF0D1F1C)
val YikeSecondaryDark = Color(0xFFB2CCC7)
val YikeOnSecondaryDark = Color(0xFF1D3531)
val YikeSecondaryContainerDark = Color(0xFF344C48)
val YikeOnSecondaryContainerDark = Color(0xFFCEE8E3)
val YikeTertiary = Color(0xFF9A4D12)
val YikeOnTertiary = Color(0xFFFFFFFF)
val YikeTertiaryContainer = Color(0xFFFFDBC7)
val YikeOnTertiaryContainer = Color(0xFF3C1600)
val YikeTertiaryDark = Color(0xFFFFB784)
val YikeOnTertiaryDark = Color(0xFF5A2900)
val YikeTertiaryContainerDark = Color(0xFF7B3A00)
val YikeOnTertiaryContainerDark = Color(0xFFFFDBC7)
val YikeError = Color(0xFFBA1A1A)
val YikeOnError = Color(0xFFFFFFFF)
val YikeErrorContainer = Color(0xFFFFDAD6)
val YikeOnErrorContainer = Color(0xFF410002)
val YikeErrorDark = Color(0xFFFFB4AB)
val YikeOnErrorDark = Color(0xFF690005)
val YikeErrorContainerDark = Color(0xFF93000A)
val YikeOnErrorContainerDark = Color(0xFFFFDAD6)
val YikeSurface = Color(0xFFF6FBF9)
val YikeSurfaceContainer = Color(0xFFEDF3F1)
val YikeSurfaceContainerHigh = Color(0xFFE6ECEA)
val YikeSurfaceContainerHighest = Color(0xFFDFE5E3)
val YikeBackground = Color(0xFFEEF4F2)
val YikeSurfaceDark = Color(0xFF0F1514)
val YikeSurfaceContainerDark = Color(0xFF1B2120)
val YikeSurfaceContainerHighDark = Color(0xFF252B2A)
val YikeSurfaceContainerHighestDark = Color(0xFF303635)
val YikeBackgroundDark = Color(0xFF0A100F)
val YikeOutline = Color(0xFF6F7977)
val YikeOutlineVariant = Color(0xFFBEC9C6)
val YikeText = Color(0xFF161D1C)
val YikeTextMuted = Color(0xFF52615E)
val YikeOutlineDark = Color(0xFF889390)
val YikeOutlineVariantDark = Color(0xFF3F4947)
val YikeTextDark = Color(0xFFDEE4E2)
val YikeTextMutedDark = Color(0xFFBDC9C6)
val YikeSuccess = Color(0xFF2E7D32)
val YikeSuccessContainer = Color(0xFFD9F3D8)
val YikeWarningContainer = Color(0xFFFFF1D6)
val YikeCriticalContainer = Color(0xFFFFE1DF)
val YikeBestContainer = Color(0xFFD1F5EF)
val YikeSuccessDark = Color(0xFF8BD48F)
val YikeSuccessContainerDark = Color(0xFF1D4D22)
val YikeWarningContainerDark = Color(0xFF5D4B1F)
val YikeCriticalContainerDark = Color(0xFF5F3431)
val YikeBestContainerDark = Color(0xFF1A4F49)
val YikeSurfaceTint = Color(0x140B6F69)
val YikeSurfaceTintDark = Color(0x2280D5CE)
